id: D9B12C296
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-17T10:34:57+00:00'
last_modified: '2022-05-26T06:09:45.012225+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    c115:
      image_group_id: I1PD95846
      title: ཡོན་ཏན་མཐའ་ཡས་པར་བསྟོད་པའི་དོན་གྱི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1539
      order: 1
      base_file: c115.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
