id: P9DF0DACA
initial_creation_type: ocr
source_metadata:
  volumes:
    d369dfa05d1040d7a56e6a4b67b02a72:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཡོན་ཏན་མཐའ་ཡས་པར་བསྟོད་པའི་དོན་གྱི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1539
      volume_number: 1
